name: Deploy Cloud Resume to GCP

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    # Autentificare securizată prin Workload Identity Federation (FĂRĂ CHEI SECRETE)
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: 'project-1f84e1ec-fa9e-4a59-9ba'
        workload_identity_provider: 'projects/328912043975/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-deployer@project-1f84e1ec-fa9e-4a59-9ba.iam.gserviceaccount.com'

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Terraform Clean & Init
      env:
        GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: 'github-actions-deployer@project-1f84e1ec-fa9e-4a59-9ba.iam.gserviceaccount.com'
      run: |
        rm -rf .terraform*
        terraform init -reconfigure
        terraform validate

    - name: Terraform Apply
      env:
        GOOGLE_IMPERSONATE_SERVICE_ACCOUNT: 'github-actions-deployer@project-1f84e1ec-fa9e-4a59-9ba.iam.gserviceaccount.com'
      run: terraform apply -auto-approve -input=false

    # Sincronizarea fișierului index.html cu noul bucket creat în main.tf
    - name: Deploy Frontend to GCP Storage
      run: |
        gsutil cp index.html gs://danielone1987-cloud-resume-2026/index.html



